version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/Server"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
